root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  # bin = "CONFIG_NAME=DEBUG-CORE ./build/bin/weblens"
  cmd = "./scripts/startWeblens"
  # cmd = "go build -gcflags=\"all=-N -l\" -race -o ./build/bin/weblens ./cmd/weblens"
  delay = 1000
  exclude_dir = ["ui", "build"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "LOG_FORMAT=dev APP_ROOT=$PWD GORACE='halt_on_error=1' CGO_CFLAGS_ALLOW='-Xpreprocessor' WEBLENS_LOG_LEVEL=trace WEBLENS_UI_PATH=./ui/dist/ WEBLENS_CACHE_PATH=./build/fs/core/cache/ WEBLENS_DATA_PATH=./build/fs/core/data/ ./build/bin/weblens"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "./build/logs/weblens-build.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
