/*
Weblens API

Testing FolderAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ethanrous/weblens/api"
)

func Test_openapi_FolderAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FolderAPIService CreateFolder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FolderAPI.CreateFolder(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FolderAPIService GetFolder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var folderID string

		resp, httpRes, err := apiClient.FolderAPI.GetFolder(context.Background(), folderID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FolderAPIService GetFolderHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fileID string

		resp, httpRes, err := apiClient.FolderAPI.GetFolderHistory(context.Background(), fileID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FolderAPIService ScanFolder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.FolderAPI.ScanFolder(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FolderAPIService SetFolderCover", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var folderID string

		httpRes, err := apiClient.FolderAPI.SetFolderCover(context.Background(), folderID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
