services:
  weblens:
    container_name: weblens
    image: ethrous/weblens:latest
    ports:
      - 8080:8080
    environment:
      WEBLENS_MONGODB_URI: "mongodb://weblens-mongo:27017/?directConnection=true"
      WEBLENS_DATA_PATH: "/data"
      WEBLENS_CACHE_PATH: "/cache"
    volumes:
      - ${DATA_HOST_PATH}:/data
      - ${CACHE_HOST_PATH}:/cache
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    container_name: weblens-mongo
    image: mongodb/mongodb-atlas-local:8.2.5
    hostname: mongo.weblens
    ports:
      - 27017:27017
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        if [ ! -f /data/configdb/keyfile ]; then
          tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c 756 > /data/configdb/keyfile
          chmod 400 /data/configdb/keyfile
        fi
        exec /usr/local/bin/runner server
    volumes:
      - ${DATABASE_HOST_PATH}/mongod:/data/db
      - ${DATABASE_HOST_PATH}/configdb:/data/configdb
      - ${DATABASE_HOST_PATH}/mongot:/data/mongot
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" && bash -c 'echo > /dev/tcp/localhost/27027'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
