#!/bin/bash

if [[ ! -e ./cmd ]]; then
  echo "ERR Could not find ./cmd directory, are you at the root of the repo? i.e. ~/repos/weblens and not ~/repos/weblens/scripts"
  exit 1
fi

if [[ ! -e ./build/bin ]]; then
  mkdir -p ./build/bin
fi

restart=false
trace=false
config_name=$CONFIG_NAME

while getopts "trc:" opt; do
  case $opt in
    t) trace=true
    ;;
    r) restart=true
    ;;
    c) config_name="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac

  case $OPTARG in
    -*) echo "Option $opt needs a valid argument"
    exit 1
    ;;
  esac
done

if [[ -z "$config_name" ]]; then
  export config_name="DEBUG-CORE"
fi

printf "Using config: $config_name"
if [[ $trace == true ]]; then
  do_trace="trace"
  printf " +trace"
fi
printf "\n"

while true; do
  rm -f ./build/bin/weblens

  go build -gcflags="-N -l" -race -o ./build/bin/weblens ./cmd/weblens/main.go

  if [[ ! -e ./build/bin/weblens ]]; then
    echo "Failed to build Weblens, exiting..."
    exit 1
  fi

  APP_ROOT=$(pwd) CONFIG_NAME=$config_name LOG_LEVEL=$do_trace ./build/bin/weblens
  exit=$?

  if [[ $restart == false ]] || [[ $exit == 11 ]]; then
    break
  fi
  clear

done

