#!/bin/bash

if [[ ! -e ./scripts ]]; then
  echo "ERR Could not find ./scripts directory, are you at the root of the repo? i.e. ~/repos/weblens and not ~/repos/weblens/scripts"
  exit 1
fi

printf "Generating swagger docs..."
if ! swag init --pd -g server.go -d ./http -q &>./build/logs/swag.log; then
  echo "FAILED"
  cat ./build/logs/swag.log
  echo "########## ^ Swag Init Logs ^ ##########"
  exit 1
fi
echo "DONE"
printf "########## END OF SWAG INIT ##########\n\n" >>./build/logs/swag.log

printf "Generating typescript api..."
export TS_POST_PROCESS_FILE="node ./ui/node_modules/prettier/bin/prettier.cjs --write"
if ! openapi-generator generate --enable-post-process-file -i docs/swagger.json -g typescript-axios -o ./ui/src/api/swag >>./build/logs/swag.log; then
  echo "FAILED"
  cat ./build/logs/swag.log
  echo "########## ^ Openapi Generator Logs ^ ##########"

  echo "openapi-generator (typescript) failed"
  exit 1
fi
echo "DONE"
