#!/bin/bash

if [[ ! -e ./scripts ]]; then
    echo "ERR Could not find ./scripts directory, are you at the root of the repo? i.e. ~/repos/weblens and not ~/repos/weblens/scripts"
    exit 1
fi

printf "Generating swagger docs..."
if ! swag init --pd -g router.go -d './routers/router,./routers/api/v1' -q &>./build/logs/swag.log; then
    echo "FAILED"
    cat ./build/logs/swag.log
    echo "########## ^ Swag Init Logs ^ ##########"
    exit 1
fi
echo "DONE"
printf "########## END OF SWAG INIT ##########\n\n" >>./build/logs/swag.log

printf "Generating typescript api..."
# export TS_POST_PROCESS_FILE="prettier --write"
if ! openapi-generator generate -i docs/swagger.json -g typescript-axios -o ./ui/src/api/swag --additional-properties=importFileExtension=".js" >>./build/logs/swag-typescript.log; then
    echo "FAILED"
    cat ./build/logs/swag-typescript.log
    echo "########## ^ Openapi Generator Logs ^ ##########"

    echo "openapi-generator (typescript) failed"
    exit 1
fi
echo "DONE"

printf "Generating go api..."
rm ./api/*.go
if ! openapi-generator generate -i docs/swagger.json -g go --git-user-id ethanrous --git-repo-id weblens/api -o ./api/ >>./build/logs/swag-go.log; then
    echo "FAILED"
    cat ./build/logs/swag-go.log
    echo "########## ^ Openapi Generator Logs ^ ##########"

    echo "openapi-generator (go) failed"
    exit 1
fi
echo "DONE"
