#!/bin/bash

if [[ ! -e ./ui ]]; then
  echo "ERR Could not find ./ui directory, are you at the root of the repo? i.e. ~/repos/weblens and not ~/repos/weblens/scripts"
  exit 1
fi

remote_tests=false
while [ "${1:-}" != "" ]; do
  case "$1" in
  "-r" | "--remoteTests")
    remote_tests=true
    ;;
  esac
  shift
done

if [[ ! -e ./ui/dist/index.html ]]; then
  cd ui || exit
  export VITE_APP_BUILD_TAG=test
  export VITE_BUILD=true
  npm install
  npm run build
  cd .. || exit
fi

if [[ $remote_tests == true ]] || [[ $REMOTE_TESTS == true ]]; then
  export REMOTE_TESTS=true
  echo "Setting up remote tests ..."
  if ! source ./scripts/setupRemoteTests; then
    echo "ERR Failed to setup remote tests, not running tests"
    exit 1
  fi
fi

target=$1
if [[ -z "$target" ]]; then
  target="./..."
fi

echo "Running tests ..."
(
  set -o pipefail
  APP_ROOT=$PWD CONFIG_PATH=$PWD/config CONFIG_NAME=TEST go test -v "$target" | grep -v -e CONT -e PAUSE | grep --color=always -e "^" -e "FAIL" | GREP_COLOR="1;32" grep --color=always -e "^" -e "PASS"
)
