/*
Weblens API

Programmatic access to the Weblens server

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// HistoryFileActionType the model 'HistoryFileActionType'
type HistoryFileActionType string

// List of history.FileActionType
const (
	FileCreate HistoryFileActionType = "fileCreate"
	FileMove HistoryFileActionType = "fileMove"
	FileSizeChange HistoryFileActionType = "fileSizeChange"
	Backup HistoryFileActionType = "backup"
	FileDelete HistoryFileActionType = "fileDelete"
	FileRestore HistoryFileActionType = "fileRestore"
)

// All allowed values of HistoryFileActionType enum
var AllowedHistoryFileActionTypeEnumValues = []HistoryFileActionType{
	"fileCreate",
	"fileMove",
	"fileSizeChange",
	"backup",
	"fileDelete",
	"fileRestore",
}

func (v *HistoryFileActionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := HistoryFileActionType(value)
	for _, existing := range AllowedHistoryFileActionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid HistoryFileActionType", value)
}

// NewHistoryFileActionTypeFromValue returns a pointer to a valid HistoryFileActionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewHistoryFileActionTypeFromValue(v string) (*HistoryFileActionType, error) {
	ev := HistoryFileActionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for HistoryFileActionType: valid values are %v", v, AllowedHistoryFileActionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v HistoryFileActionType) IsValid() bool {
	for _, existing := range AllowedHistoryFileActionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to history.FileActionType value
func (v HistoryFileActionType) Ptr() *HistoryFileActionType {
	return &v
}

type NullableHistoryFileActionType struct {
	value *HistoryFileActionType
	isSet bool
}

func (v NullableHistoryFileActionType) Get() *HistoryFileActionType {
	return v.value
}

func (v *NullableHistoryFileActionType) Set(val *HistoryFileActionType) {
	v.value = val
	v.isSet = true
}

func (v NullableHistoryFileActionType) IsSet() bool {
	return v.isSet
}

func (v *NullableHistoryFileActionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHistoryFileActionType(val *HistoryFileActionType) *NullableHistoryFileActionType {
	return &NullableHistoryFileActionType{value: val, isSet: true}
}

func (v NullableHistoryFileActionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHistoryFileActionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

