/*
Weblens API

Programmatic access to the Weblens server

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HistoryFileAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HistoryFileAction{}

// HistoryFileAction struct for HistoryFileAction
type HistoryFileAction struct {
	ActionType *string `json:"actionType,omitempty"`
	ContentID *string `json:"contentID,omitempty"`
	DestinationPath *WlfsFilepath `json:"destinationPath,omitempty"`
	// The user or system that performed the action
	Doer *string `json:"doer,omitempty"`
	EventID *string `json:"eventID,omitempty"`
	FileID *string `json:"fileID,omitempty"`
	Filepath *WlfsFilepath `json:"filepath,omitempty"`
	Id *string `json:"id,omitempty"`
	OriginPath *WlfsFilepath `json:"originPath,omitempty"`
	Size *int32 `json:"size,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
	TowerID *string `json:"towerID,omitempty"`
}

// NewHistoryFileAction instantiates a new HistoryFileAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHistoryFileAction() *HistoryFileAction {
	this := HistoryFileAction{}
	return &this
}

// NewHistoryFileActionWithDefaults instantiates a new HistoryFileAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHistoryFileActionWithDefaults() *HistoryFileAction {
	this := HistoryFileAction{}
	return &this
}

// GetActionType returns the ActionType field value if set, zero value otherwise.
func (o *HistoryFileAction) GetActionType() string {
	if o == nil || IsNil(o.ActionType) {
		var ret string
		return ret
	}
	return *o.ActionType
}

// GetActionTypeOk returns a tuple with the ActionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetActionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ActionType) {
		return nil, false
	}
	return o.ActionType, true
}

// HasActionType returns a boolean if a field has been set.
func (o *HistoryFileAction) HasActionType() bool {
	if o != nil && !IsNil(o.ActionType) {
		return true
	}

	return false
}

// SetActionType gets a reference to the given string and assigns it to the ActionType field.
func (o *HistoryFileAction) SetActionType(v string) {
	o.ActionType = &v
}

// GetContentID returns the ContentID field value if set, zero value otherwise.
func (o *HistoryFileAction) GetContentID() string {
	if o == nil || IsNil(o.ContentID) {
		var ret string
		return ret
	}
	return *o.ContentID
}

// GetContentIDOk returns a tuple with the ContentID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetContentIDOk() (*string, bool) {
	if o == nil || IsNil(o.ContentID) {
		return nil, false
	}
	return o.ContentID, true
}

// HasContentID returns a boolean if a field has been set.
func (o *HistoryFileAction) HasContentID() bool {
	if o != nil && !IsNil(o.ContentID) {
		return true
	}

	return false
}

// SetContentID gets a reference to the given string and assigns it to the ContentID field.
func (o *HistoryFileAction) SetContentID(v string) {
	o.ContentID = &v
}

// GetDestinationPath returns the DestinationPath field value if set, zero value otherwise.
func (o *HistoryFileAction) GetDestinationPath() WlfsFilepath {
	if o == nil || IsNil(o.DestinationPath) {
		var ret WlfsFilepath
		return ret
	}
	return *o.DestinationPath
}

// GetDestinationPathOk returns a tuple with the DestinationPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetDestinationPathOk() (*WlfsFilepath, bool) {
	if o == nil || IsNil(o.DestinationPath) {
		return nil, false
	}
	return o.DestinationPath, true
}

// HasDestinationPath returns a boolean if a field has been set.
func (o *HistoryFileAction) HasDestinationPath() bool {
	if o != nil && !IsNil(o.DestinationPath) {
		return true
	}

	return false
}

// SetDestinationPath gets a reference to the given WlfsFilepath and assigns it to the DestinationPath field.
func (o *HistoryFileAction) SetDestinationPath(v WlfsFilepath) {
	o.DestinationPath = &v
}

// GetDoer returns the Doer field value if set, zero value otherwise.
func (o *HistoryFileAction) GetDoer() string {
	if o == nil || IsNil(o.Doer) {
		var ret string
		return ret
	}
	return *o.Doer
}

// GetDoerOk returns a tuple with the Doer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetDoerOk() (*string, bool) {
	if o == nil || IsNil(o.Doer) {
		return nil, false
	}
	return o.Doer, true
}

// HasDoer returns a boolean if a field has been set.
func (o *HistoryFileAction) HasDoer() bool {
	if o != nil && !IsNil(o.Doer) {
		return true
	}

	return false
}

// SetDoer gets a reference to the given string and assigns it to the Doer field.
func (o *HistoryFileAction) SetDoer(v string) {
	o.Doer = &v
}

// GetEventID returns the EventID field value if set, zero value otherwise.
func (o *HistoryFileAction) GetEventID() string {
	if o == nil || IsNil(o.EventID) {
		var ret string
		return ret
	}
	return *o.EventID
}

// GetEventIDOk returns a tuple with the EventID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetEventIDOk() (*string, bool) {
	if o == nil || IsNil(o.EventID) {
		return nil, false
	}
	return o.EventID, true
}

// HasEventID returns a boolean if a field has been set.
func (o *HistoryFileAction) HasEventID() bool {
	if o != nil && !IsNil(o.EventID) {
		return true
	}

	return false
}

// SetEventID gets a reference to the given string and assigns it to the EventID field.
func (o *HistoryFileAction) SetEventID(v string) {
	o.EventID = &v
}

// GetFileID returns the FileID field value if set, zero value otherwise.
func (o *HistoryFileAction) GetFileID() string {
	if o == nil || IsNil(o.FileID) {
		var ret string
		return ret
	}
	return *o.FileID
}

// GetFileIDOk returns a tuple with the FileID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetFileIDOk() (*string, bool) {
	if o == nil || IsNil(o.FileID) {
		return nil, false
	}
	return o.FileID, true
}

// HasFileID returns a boolean if a field has been set.
func (o *HistoryFileAction) HasFileID() bool {
	if o != nil && !IsNil(o.FileID) {
		return true
	}

	return false
}

// SetFileID gets a reference to the given string and assigns it to the FileID field.
func (o *HistoryFileAction) SetFileID(v string) {
	o.FileID = &v
}

// GetFilepath returns the Filepath field value if set, zero value otherwise.
func (o *HistoryFileAction) GetFilepath() WlfsFilepath {
	if o == nil || IsNil(o.Filepath) {
		var ret WlfsFilepath
		return ret
	}
	return *o.Filepath
}

// GetFilepathOk returns a tuple with the Filepath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetFilepathOk() (*WlfsFilepath, bool) {
	if o == nil || IsNil(o.Filepath) {
		return nil, false
	}
	return o.Filepath, true
}

// HasFilepath returns a boolean if a field has been set.
func (o *HistoryFileAction) HasFilepath() bool {
	if o != nil && !IsNil(o.Filepath) {
		return true
	}

	return false
}

// SetFilepath gets a reference to the given WlfsFilepath and assigns it to the Filepath field.
func (o *HistoryFileAction) SetFilepath(v WlfsFilepath) {
	o.Filepath = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *HistoryFileAction) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *HistoryFileAction) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *HistoryFileAction) SetId(v string) {
	o.Id = &v
}

// GetOriginPath returns the OriginPath field value if set, zero value otherwise.
func (o *HistoryFileAction) GetOriginPath() WlfsFilepath {
	if o == nil || IsNil(o.OriginPath) {
		var ret WlfsFilepath
		return ret
	}
	return *o.OriginPath
}

// GetOriginPathOk returns a tuple with the OriginPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetOriginPathOk() (*WlfsFilepath, bool) {
	if o == nil || IsNil(o.OriginPath) {
		return nil, false
	}
	return o.OriginPath, true
}

// HasOriginPath returns a boolean if a field has been set.
func (o *HistoryFileAction) HasOriginPath() bool {
	if o != nil && !IsNil(o.OriginPath) {
		return true
	}

	return false
}

// SetOriginPath gets a reference to the given WlfsFilepath and assigns it to the OriginPath field.
func (o *HistoryFileAction) SetOriginPath(v WlfsFilepath) {
	o.OriginPath = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *HistoryFileAction) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *HistoryFileAction) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *HistoryFileAction) SetSize(v int32) {
	o.Size = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *HistoryFileAction) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp) {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *HistoryFileAction) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *HistoryFileAction) SetTimestamp(v string) {
	o.Timestamp = &v
}

// GetTowerID returns the TowerID field value if set, zero value otherwise.
func (o *HistoryFileAction) GetTowerID() string {
	if o == nil || IsNil(o.TowerID) {
		var ret string
		return ret
	}
	return *o.TowerID
}

// GetTowerIDOk returns a tuple with the TowerID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryFileAction) GetTowerIDOk() (*string, bool) {
	if o == nil || IsNil(o.TowerID) {
		return nil, false
	}
	return o.TowerID, true
}

// HasTowerID returns a boolean if a field has been set.
func (o *HistoryFileAction) HasTowerID() bool {
	if o != nil && !IsNil(o.TowerID) {
		return true
	}

	return false
}

// SetTowerID gets a reference to the given string and assigns it to the TowerID field.
func (o *HistoryFileAction) SetTowerID(v string) {
	o.TowerID = &v
}

func (o HistoryFileAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HistoryFileAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActionType) {
		toSerialize["actionType"] = o.ActionType
	}
	if !IsNil(o.ContentID) {
		toSerialize["contentID"] = o.ContentID
	}
	if !IsNil(o.DestinationPath) {
		toSerialize["destinationPath"] = o.DestinationPath
	}
	if !IsNil(o.Doer) {
		toSerialize["doer"] = o.Doer
	}
	if !IsNil(o.EventID) {
		toSerialize["eventID"] = o.EventID
	}
	if !IsNil(o.FileID) {
		toSerialize["fileID"] = o.FileID
	}
	if !IsNil(o.Filepath) {
		toSerialize["filepath"] = o.Filepath
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OriginPath) {
		toSerialize["originPath"] = o.OriginPath
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.TowerID) {
		toSerialize["towerID"] = o.TowerID
	}
	return toSerialize, nil
}

type NullableHistoryFileAction struct {
	value *HistoryFileAction
	isSet bool
}

func (v NullableHistoryFileAction) Get() *HistoryFileAction {
	return v.value
}

func (v *NullableHistoryFileAction) Set(val *HistoryFileAction) {
	v.value = val
	v.isSet = true
}

func (v NullableHistoryFileAction) IsSet() bool {
	return v.isSet
}

func (v *NullableHistoryFileAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHistoryFileAction(val *HistoryFileAction) *NullableHistoryFileAction {
	return &NullableHistoryFileAction{value: val, isSet: true}
}

func (v NullableHistoryFileAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHistoryFileAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


