/*
Weblens API

Programmatic access to the Weblens server

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FileIDArrayInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileIDArrayInfo{}

// FileIDArrayInfo struct for FileIDArrayInfo
type FileIDArrayInfo struct {
	FileIDs []string `json:"fileIDs,omitempty"`
}

// NewFileIDArrayInfo instantiates a new FileIDArrayInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileIDArrayInfo() *FileIDArrayInfo {
	this := FileIDArrayInfo{}
	return &this
}

// NewFileIDArrayInfoWithDefaults instantiates a new FileIDArrayInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileIDArrayInfoWithDefaults() *FileIDArrayInfo {
	this := FileIDArrayInfo{}
	return &this
}

// GetFileIDs returns the FileIDs field value if set, zero value otherwise.
func (o *FileIDArrayInfo) GetFileIDs() []string {
	if o == nil || IsNil(o.FileIDs) {
		var ret []string
		return ret
	}
	return o.FileIDs
}

// GetFileIDsOk returns a tuple with the FileIDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileIDArrayInfo) GetFileIDsOk() ([]string, bool) {
	if o == nil || IsNil(o.FileIDs) {
		return nil, false
	}
	return o.FileIDs, true
}

// HasFileIDs returns a boolean if a field has been set.
func (o *FileIDArrayInfo) HasFileIDs() bool {
	if o != nil && !IsNil(o.FileIDs) {
		return true
	}

	return false
}

// SetFileIDs gets a reference to the given []string and assigns it to the FileIDs field.
func (o *FileIDArrayInfo) SetFileIDs(v []string) {
	o.FileIDs = v
}

func (o FileIDArrayInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileIDArrayInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FileIDs) {
		toSerialize["fileIDs"] = o.FileIDs
	}
	return toSerialize, nil
}

type NullableFileIDArrayInfo struct {
	value *FileIDArrayInfo
	isSet bool
}

func (v NullableFileIDArrayInfo) Get() *FileIDArrayInfo {
	return v.value
}

func (v *NullableFileIDArrayInfo) Set(val *FileIDArrayInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFileIDArrayInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFileIDArrayInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileIDArrayInfo(val *FileIDArrayInfo) *NullableFileIDArrayInfo {
	return &NullableFileIDArrayInfo{value: val, isSet: true}
}

func (v NullableFileIDArrayInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileIDArrayInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


