/*
Weblens API

Programmatic access to the Weblens server

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TaskExitStatus the model 'TaskExitStatus'
type TaskExitStatus string

// List of task.ExitStatus
const (
	TaskNoStatus TaskExitStatus = ""
	TaskSuccess TaskExitStatus = "success"
	TaskCanceled TaskExitStatus = "cancelled"
	TaskError TaskExitStatus = "error"
)

// All allowed values of TaskExitStatus enum
var AllowedTaskExitStatusEnumValues = []TaskExitStatus{
	"",
	"success",
	"cancelled",
	"error",
}

func (v *TaskExitStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TaskExitStatus(value)
	for _, existing := range AllowedTaskExitStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TaskExitStatus", value)
}

// NewTaskExitStatusFromValue returns a pointer to a valid TaskExitStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTaskExitStatusFromValue(v string) (*TaskExitStatus, error) {
	ev := TaskExitStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TaskExitStatus: valid values are %v", v, AllowedTaskExitStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TaskExitStatus) IsValid() bool {
	for _, existing := range AllowedTaskExitStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to task.ExitStatus value
func (v TaskExitStatus) Ptr() *TaskExitStatus {
	return &v
}

type NullableTaskExitStatus struct {
	value *TaskExitStatus
	isSet bool
}

func (v NullableTaskExitStatus) Get() *TaskExitStatus {
	return v.value
}

func (v *NullableTaskExitStatus) Set(val *TaskExitStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskExitStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskExitStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskExitStatus(val *TaskExitStatus) *NullableTaskExitStatus {
	return &NullableTaskExitStatus{value: val, isSet: true}
}

func (v NullableTaskExitStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskExitStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

