/*
Weblens API

Programmatic access to the Weblens server

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WLResponseInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WLResponseInfo{}

// WLResponseInfo struct for WLResponseInfo
type WLResponseInfo struct {
	Message *string `json:"message,omitempty"`
}

// NewWLResponseInfo instantiates a new WLResponseInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWLResponseInfo() *WLResponseInfo {
	this := WLResponseInfo{}
	return &this
}

// NewWLResponseInfoWithDefaults instantiates a new WLResponseInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWLResponseInfoWithDefaults() *WLResponseInfo {
	this := WLResponseInfo{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *WLResponseInfo) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WLResponseInfo) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *WLResponseInfo) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *WLResponseInfo) SetMessage(v string) {
	o.Message = &v
}

func (o WLResponseInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WLResponseInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableWLResponseInfo struct {
	value *WLResponseInfo
	isSet bool
}

func (v NullableWLResponseInfo) Get() *WLResponseInfo {
	return v.value
}

func (v *NullableWLResponseInfo) Set(val *WLResponseInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableWLResponseInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableWLResponseInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWLResponseInfo(val *WLResponseInfo) *NullableWLResponseInfo {
	return &NullableWLResponseInfo{value: val, isSet: true}
}

func (v NullableWLResponseInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWLResponseInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


