/*
Weblens API

Programmatic access to the Weblens server

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserInfo{}

// UserInfo struct for UserInfo
type UserInfo struct {
	Activated bool `json:"activated"`
	FullName string `json:"fullName"`
	HomeID string `json:"homeID"`
	IsOnline *bool `json:"isOnline,omitempty"`
	PermissionLevel int32 `json:"permissionLevel"`
	Token *string `json:"token,omitempty"`
	TrashID string `json:"trashID"`
	UpdatedAt int64 `json:"updatedAt"`
	Username string `json:"username"`
}

type _UserInfo UserInfo

// NewUserInfo instantiates a new UserInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserInfo(activated bool, fullName string, homeID string, permissionLevel int32, trashID string, updatedAt int64, username string) *UserInfo {
	this := UserInfo{}
	this.Activated = activated
	this.FullName = fullName
	this.HomeID = homeID
	this.PermissionLevel = permissionLevel
	this.TrashID = trashID
	this.UpdatedAt = updatedAt
	this.Username = username
	return &this
}

// NewUserInfoWithDefaults instantiates a new UserInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserInfoWithDefaults() *UserInfo {
	this := UserInfo{}
	return &this
}

// GetActivated returns the Activated field value
func (o *UserInfo) GetActivated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Activated
}

// GetActivatedOk returns a tuple with the Activated field value
// and a boolean to check if the value has been set.
func (o *UserInfo) GetActivatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Activated, true
}

// SetActivated sets field value
func (o *UserInfo) SetActivated(v bool) {
	o.Activated = v
}

// GetFullName returns the FullName field value
func (o *UserInfo) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *UserInfo) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *UserInfo) SetFullName(v string) {
	o.FullName = v
}

// GetHomeID returns the HomeID field value
func (o *UserInfo) GetHomeID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HomeID
}

// GetHomeIDOk returns a tuple with the HomeID field value
// and a boolean to check if the value has been set.
func (o *UserInfo) GetHomeIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HomeID, true
}

// SetHomeID sets field value
func (o *UserInfo) SetHomeID(v string) {
	o.HomeID = v
}

// GetIsOnline returns the IsOnline field value if set, zero value otherwise.
func (o *UserInfo) GetIsOnline() bool {
	if o == nil || IsNil(o.IsOnline) {
		var ret bool
		return ret
	}
	return *o.IsOnline
}

// GetIsOnlineOk returns a tuple with the IsOnline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInfo) GetIsOnlineOk() (*bool, bool) {
	if o == nil || IsNil(o.IsOnline) {
		return nil, false
	}
	return o.IsOnline, true
}

// HasIsOnline returns a boolean if a field has been set.
func (o *UserInfo) HasIsOnline() bool {
	if o != nil && !IsNil(o.IsOnline) {
		return true
	}

	return false
}

// SetIsOnline gets a reference to the given bool and assigns it to the IsOnline field.
func (o *UserInfo) SetIsOnline(v bool) {
	o.IsOnline = &v
}

// GetPermissionLevel returns the PermissionLevel field value
func (o *UserInfo) GetPermissionLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PermissionLevel
}

// GetPermissionLevelOk returns a tuple with the PermissionLevel field value
// and a boolean to check if the value has been set.
func (o *UserInfo) GetPermissionLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PermissionLevel, true
}

// SetPermissionLevel sets field value
func (o *UserInfo) SetPermissionLevel(v int32) {
	o.PermissionLevel = v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *UserInfo) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInfo) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *UserInfo) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *UserInfo) SetToken(v string) {
	o.Token = &v
}

// GetTrashID returns the TrashID field value
func (o *UserInfo) GetTrashID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrashID
}

// GetTrashIDOk returns a tuple with the TrashID field value
// and a boolean to check if the value has been set.
func (o *UserInfo) GetTrashIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrashID, true
}

// SetTrashID sets field value
func (o *UserInfo) SetTrashID(v string) {
	o.TrashID = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UserInfo) GetUpdatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UserInfo) GetUpdatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UserInfo) SetUpdatedAt(v int64) {
	o.UpdatedAt = v
}

// GetUsername returns the Username field value
func (o *UserInfo) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserInfo) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserInfo) SetUsername(v string) {
	o.Username = v
}

func (o UserInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["activated"] = o.Activated
	toSerialize["fullName"] = o.FullName
	toSerialize["homeID"] = o.HomeID
	if !IsNil(o.IsOnline) {
		toSerialize["isOnline"] = o.IsOnline
	}
	toSerialize["permissionLevel"] = o.PermissionLevel
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	toSerialize["trashID"] = o.TrashID
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *UserInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"activated",
		"fullName",
		"homeID",
		"permissionLevel",
		"trashID",
		"updatedAt",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserInfo := _UserInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserInfo)

	if err != nil {
		return err
	}

	*o = UserInfo(varUserInfo)

	return err
}

type NullableUserInfo struct {
	value *UserInfo
	isSet bool
}

func (v NullableUserInfo) Get() *UserInfo {
	return v.value
}

func (v *NullableUserInfo) Set(val *UserInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableUserInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableUserInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserInfo(val *UserInfo) *NullableUserInfo {
	return &NullableUserInfo{value: val, isSet: true}
}

func (v NullableUserInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


