/*
Weblens API

Programmatic access to the Weblens server

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TagCreateTagParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagCreateTagParams{}

// TagCreateTagParams struct for TagCreateTagParams
type TagCreateTagParams struct {
	Color *string `json:"color,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewTagCreateTagParams instantiates a new TagCreateTagParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagCreateTagParams() *TagCreateTagParams {
	this := TagCreateTagParams{}
	return &this
}

// NewTagCreateTagParamsWithDefaults instantiates a new TagCreateTagParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagCreateTagParamsWithDefaults() *TagCreateTagParams {
	this := TagCreateTagParams{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *TagCreateTagParams) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagCreateTagParams) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *TagCreateTagParams) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *TagCreateTagParams) SetColor(v string) {
	o.Color = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TagCreateTagParams) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagCreateTagParams) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TagCreateTagParams) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TagCreateTagParams) SetName(v string) {
	o.Name = &v
}

func (o TagCreateTagParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagCreateTagParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableTagCreateTagParams struct {
	value *TagCreateTagParams
	isSet bool
}

func (v NullableTagCreateTagParams) Get() *TagCreateTagParams {
	return v.value
}

func (v *NullableTagCreateTagParams) Set(val *TagCreateTagParams) {
	v.value = val
	v.isSet = true
}

func (v NullableTagCreateTagParams) IsSet() bool {
	return v.isSet
}

func (v *NullableTagCreateTagParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagCreateTagParams(val *TagCreateTagParams) *NullableTagCreateTagParams {
	return &NullableTagCreateTagParams{value: val, isSet: true}
}

func (v NullableTagCreateTagParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagCreateTagParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


