/*
Weblens API

Programmatic access to the Weblens server

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GithubComEthanrousWeblensModelsTagTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComEthanrousWeblensModelsTagTag{}

// GithubComEthanrousWeblensModelsTagTag struct for GithubComEthanrousWeblensModelsTagTag
type GithubComEthanrousWeblensModelsTagTag struct {
	Color *string `json:"color,omitempty"`
	Created *string `json:"created,omitempty"`
	FileIDs []string `json:"fileIDs,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Owner *string `json:"owner,omitempty"`
	Updated *string `json:"updated,omitempty"`
}

// NewGithubComEthanrousWeblensModelsTagTag instantiates a new GithubComEthanrousWeblensModelsTagTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComEthanrousWeblensModelsTagTag() *GithubComEthanrousWeblensModelsTagTag {
	this := GithubComEthanrousWeblensModelsTagTag{}
	return &this
}

// NewGithubComEthanrousWeblensModelsTagTagWithDefaults instantiates a new GithubComEthanrousWeblensModelsTagTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComEthanrousWeblensModelsTagTagWithDefaults() *GithubComEthanrousWeblensModelsTagTag {
	this := GithubComEthanrousWeblensModelsTagTag{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *GithubComEthanrousWeblensModelsTagTag) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *GithubComEthanrousWeblensModelsTagTag) SetColor(v string) {
	o.Color = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *GithubComEthanrousWeblensModelsTagTag) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *GithubComEthanrousWeblensModelsTagTag) SetCreated(v string) {
	o.Created = &v
}

// GetFileIDs returns the FileIDs field value if set, zero value otherwise.
func (o *GithubComEthanrousWeblensModelsTagTag) GetFileIDs() []string {
	if o == nil || IsNil(o.FileIDs) {
		var ret []string
		return ret
	}
	return o.FileIDs
}

// GetFileIDsOk returns a tuple with the FileIDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) GetFileIDsOk() ([]string, bool) {
	if o == nil || IsNil(o.FileIDs) {
		return nil, false
	}
	return o.FileIDs, true
}

// HasFileIDs returns a boolean if a field has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) HasFileIDs() bool {
	if o != nil && !IsNil(o.FileIDs) {
		return true
	}

	return false
}

// SetFileIDs gets a reference to the given []string and assigns it to the FileIDs field.
func (o *GithubComEthanrousWeblensModelsTagTag) SetFileIDs(v []string) {
	o.FileIDs = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GithubComEthanrousWeblensModelsTagTag) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GithubComEthanrousWeblensModelsTagTag) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GithubComEthanrousWeblensModelsTagTag) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GithubComEthanrousWeblensModelsTagTag) SetName(v string) {
	o.Name = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *GithubComEthanrousWeblensModelsTagTag) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *GithubComEthanrousWeblensModelsTagTag) SetOwner(v string) {
	o.Owner = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *GithubComEthanrousWeblensModelsTagTag) GetUpdated() string {
	if o == nil || IsNil(o.Updated) {
		var ret string
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) GetUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *GithubComEthanrousWeblensModelsTagTag) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given string and assigns it to the Updated field.
func (o *GithubComEthanrousWeblensModelsTagTag) SetUpdated(v string) {
	o.Updated = &v
}

func (o GithubComEthanrousWeblensModelsTagTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComEthanrousWeblensModelsTagTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.FileIDs) {
		toSerialize["fileIDs"] = o.FileIDs
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableGithubComEthanrousWeblensModelsTagTag struct {
	value *GithubComEthanrousWeblensModelsTagTag
	isSet bool
}

func (v NullableGithubComEthanrousWeblensModelsTagTag) Get() *GithubComEthanrousWeblensModelsTagTag {
	return v.value
}

func (v *NullableGithubComEthanrousWeblensModelsTagTag) Set(val *GithubComEthanrousWeblensModelsTagTag) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComEthanrousWeblensModelsTagTag) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComEthanrousWeblensModelsTagTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComEthanrousWeblensModelsTagTag(val *GithubComEthanrousWeblensModelsTagTag) *NullableGithubComEthanrousWeblensModelsTagTag {
	return &NullableGithubComEthanrousWeblensModelsTagTag{value: val, isSet: true}
}

func (v NullableGithubComEthanrousWeblensModelsTagTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComEthanrousWeblensModelsTagTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


