/*
Weblens API

Programmatic access to the Weblens server

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserInfoArchive type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserInfoArchive{}

// UserInfoArchive struct for UserInfoArchive
type UserInfoArchive struct {
	Activated bool `json:"activated"`
	FullName string `json:"fullName"`
	HomeId string `json:"homeId"`
	IsOnline *bool `json:"isOnline,omitempty"`
	Password *string `json:"password,omitempty"`
	PermissionLevel int32 `json:"permissionLevel"`
	Token *string `json:"token,omitempty"`
	TrashId string `json:"trashId"`
	Username string `json:"username"`
}

type _UserInfoArchive UserInfoArchive

// NewUserInfoArchive instantiates a new UserInfoArchive object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserInfoArchive(activated bool, fullName string, homeId string, permissionLevel int32, trashId string, username string) *UserInfoArchive {
	this := UserInfoArchive{}
	this.Activated = activated
	this.FullName = fullName
	this.HomeId = homeId
	this.PermissionLevel = permissionLevel
	this.TrashId = trashId
	this.Username = username
	return &this
}

// NewUserInfoArchiveWithDefaults instantiates a new UserInfoArchive object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserInfoArchiveWithDefaults() *UserInfoArchive {
	this := UserInfoArchive{}
	return &this
}

// GetActivated returns the Activated field value
func (o *UserInfoArchive) GetActivated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Activated
}

// GetActivatedOk returns a tuple with the Activated field value
// and a boolean to check if the value has been set.
func (o *UserInfoArchive) GetActivatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Activated, true
}

// SetActivated sets field value
func (o *UserInfoArchive) SetActivated(v bool) {
	o.Activated = v
}

// GetFullName returns the FullName field value
func (o *UserInfoArchive) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *UserInfoArchive) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *UserInfoArchive) SetFullName(v string) {
	o.FullName = v
}

// GetHomeId returns the HomeId field value
func (o *UserInfoArchive) GetHomeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HomeId
}

// GetHomeIdOk returns a tuple with the HomeId field value
// and a boolean to check if the value has been set.
func (o *UserInfoArchive) GetHomeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HomeId, true
}

// SetHomeId sets field value
func (o *UserInfoArchive) SetHomeId(v string) {
	o.HomeId = v
}

// GetIsOnline returns the IsOnline field value if set, zero value otherwise.
func (o *UserInfoArchive) GetIsOnline() bool {
	if o == nil || IsNil(o.IsOnline) {
		var ret bool
		return ret
	}
	return *o.IsOnline
}

// GetIsOnlineOk returns a tuple with the IsOnline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInfoArchive) GetIsOnlineOk() (*bool, bool) {
	if o == nil || IsNil(o.IsOnline) {
		return nil, false
	}
	return o.IsOnline, true
}

// HasIsOnline returns a boolean if a field has been set.
func (o *UserInfoArchive) HasIsOnline() bool {
	if o != nil && !IsNil(o.IsOnline) {
		return true
	}

	return false
}

// SetIsOnline gets a reference to the given bool and assigns it to the IsOnline field.
func (o *UserInfoArchive) SetIsOnline(v bool) {
	o.IsOnline = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *UserInfoArchive) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInfoArchive) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *UserInfoArchive) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *UserInfoArchive) SetPassword(v string) {
	o.Password = &v
}

// GetPermissionLevel returns the PermissionLevel field value
func (o *UserInfoArchive) GetPermissionLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PermissionLevel
}

// GetPermissionLevelOk returns a tuple with the PermissionLevel field value
// and a boolean to check if the value has been set.
func (o *UserInfoArchive) GetPermissionLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PermissionLevel, true
}

// SetPermissionLevel sets field value
func (o *UserInfoArchive) SetPermissionLevel(v int32) {
	o.PermissionLevel = v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *UserInfoArchive) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInfoArchive) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *UserInfoArchive) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *UserInfoArchive) SetToken(v string) {
	o.Token = &v
}

// GetTrashId returns the TrashId field value
func (o *UserInfoArchive) GetTrashId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrashId
}

// GetTrashIdOk returns a tuple with the TrashId field value
// and a boolean to check if the value has been set.
func (o *UserInfoArchive) GetTrashIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrashId, true
}

// SetTrashId sets field value
func (o *UserInfoArchive) SetTrashId(v string) {
	o.TrashId = v
}

// GetUsername returns the Username field value
func (o *UserInfoArchive) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserInfoArchive) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserInfoArchive) SetUsername(v string) {
	o.Username = v
}

func (o UserInfoArchive) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserInfoArchive) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["activated"] = o.Activated
	toSerialize["fullName"] = o.FullName
	toSerialize["homeId"] = o.HomeId
	if !IsNil(o.IsOnline) {
		toSerialize["isOnline"] = o.IsOnline
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	toSerialize["permissionLevel"] = o.PermissionLevel
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	toSerialize["trashId"] = o.TrashId
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *UserInfoArchive) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"activated",
		"fullName",
		"homeId",
		"permissionLevel",
		"trashId",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserInfoArchive := _UserInfoArchive{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserInfoArchive)

	if err != nil {
		return err
	}

	*o = UserInfoArchive(varUserInfoArchive)

	return err
}

type NullableUserInfoArchive struct {
	value *UserInfoArchive
	isSet bool
}

func (v NullableUserInfoArchive) Get() *UserInfoArchive {
	return v.value
}

func (v *NullableUserInfoArchive) Set(val *UserInfoArchive) {
	v.value = val
	v.isSet = true
}

func (v NullableUserInfoArchive) IsSet() bool {
	return v.isSet
}

func (v *NullableUserInfoArchive) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserInfoArchive(val *UserInfoArchive) *NullableUserInfoArchive {
	return &NullableUserInfoArchive{value: val, isSet: true}
}

func (v NullableUserInfoArchive) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserInfoArchive) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


