/*
Weblens API

Programmatic access to the Weblens server

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the StructsScanBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StructsScanBody{}

// StructsScanBody struct for StructsScanBody
type StructsScanBody struct {
	Filename *string `json:"filename,omitempty"`
	FolderId *string `json:"folderId,omitempty"`
}

// NewStructsScanBody instantiates a new StructsScanBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStructsScanBody() *StructsScanBody {
	this := StructsScanBody{}
	return &this
}

// NewStructsScanBodyWithDefaults instantiates a new StructsScanBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStructsScanBodyWithDefaults() *StructsScanBody {
	this := StructsScanBody{}
	return &this
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *StructsScanBody) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructsScanBody) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *StructsScanBody) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *StructsScanBody) SetFilename(v string) {
	o.Filename = &v
}

// GetFolderId returns the FolderId field value if set, zero value otherwise.
func (o *StructsScanBody) GetFolderId() string {
	if o == nil || IsNil(o.FolderId) {
		var ret string
		return ret
	}
	return *o.FolderId
}

// GetFolderIdOk returns a tuple with the FolderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructsScanBody) GetFolderIdOk() (*string, bool) {
	if o == nil || IsNil(o.FolderId) {
		return nil, false
	}
	return o.FolderId, true
}

// HasFolderId returns a boolean if a field has been set.
func (o *StructsScanBody) HasFolderId() bool {
	if o != nil && !IsNil(o.FolderId) {
		return true
	}

	return false
}

// SetFolderId gets a reference to the given string and assigns it to the FolderId field.
func (o *StructsScanBody) SetFolderId(v string) {
	o.FolderId = &v
}

func (o StructsScanBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StructsScanBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.FolderId) {
		toSerialize["folderId"] = o.FolderId
	}
	return toSerialize, nil
}

type NullableStructsScanBody struct {
	value *StructsScanBody
	isSet bool
}

func (v NullableStructsScanBody) Get() *StructsScanBody {
	return v.value
}

func (v *NullableStructsScanBody) Set(val *StructsScanBody) {
	v.value = val
	v.isSet = true
}

func (v NullableStructsScanBody) IsSet() bool {
	return v.isSet
}

func (v *NullableStructsScanBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructsScanBody(val *StructsScanBody) *NullableStructsScanBody {
	return &NullableStructsScanBody{value: val, isSet: true}
}

func (v NullableStructsScanBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructsScanBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


